version: "3"
services:
  app:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "tamln2/frontend:latest"
    environment:
      - API=localhost:8080
    ports:
      - "3000:3000"
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=tam
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
  backend:
    build: ./demo
    image: tamln2/backend:latest
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{ "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tam?allowPublicKeyRetrieval=true&useSSL=false", 
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "12345678",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db:
